import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree, Baloo_Bhaijaan_2 } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./providers/CartContext";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Organism/Navbar";
import { ThemeProvider } from "@/components/Molecules/ThemeProvider";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const balooBhaijaan = Baloo_Bhaijaan_2({
    subsets: ["arabic"],
    weight: ["400", "500", "600", "700", "800"],
    variable: "--font-baloo",
    preload: true,
});
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn("h-full", "antialiased", balooBhaijaan.variable)}
            suppressHydrationWarning
        >
            <body className="min-h-full flex flex-col">
                <CartProvider>
                    <ThemeProvider
                        attribute={"class"}
                        defaultTheme="system"
                        enableSystem
                    >
                        <Navbar />
                        {children}
                    </ThemeProvider>
                </CartProvider>
            </body>
        </html>
    );
}
